name = "foreverplaced"
pages_build_output_dir = "./dist"

compatibility_date = "2024-12-15"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "fpinfo"
id = "14256635fae2400d96d4c0dd7653083f"

